### ISSUE TITLE
what stl libary to i install??

### ISSUE THREAD

**Issue by Kaifungamedev** [RotBotSlicer/Transform#10]
I'm trying to use the scripts but I don't know that stl library to install Just running "pip install stl" gives me this error : <br>
`Traceback (most recent call last):
  File "c:\Users\User\Documents\GitHub\Transform\Scripts for Variable Angle\Transformation_STL_var_angle.py", line 2, in <module>
    from stl import mesh
ModuleNotFoundError: No module named 'stl'`

**Comment by IgorOhrimenko** [comment]
pip install numpy-stl

**Comment by Kaifungamedev** [comment]
thanks
