### ISSUE TITLE
Prerequisites missing

### ISSUE THREAD

**Issue by Rayal** [RotBotSlicer/Transform#4]
Hi!
I tried to use the script to try out the conical slicing and noticed that there is no `requirements.txt` file.

There is also no info on the python version being used.

I assumed python3.10 and tried installing stl with pip (`pip install stl`) but this did not work.

**Comment by RotBotSlicer** [comment]
Hi
I also use Python 3.10 and for me it works well. I can not help you with installing stl. Sorry...

Regards

**Comment by Rayal** [comment]
I found out that you're using the numpy-stl library.

Please consider adding a `requirements.txt` file: `pip freeze > requirements.txt`

I believe the necessary contents are: 
```
numpy==1.23.4
numpy-stl==2.17.1
```

It makes it easier to import your code: `pip install -r requirements.txt`

**Comment by sxiii** [comment]
Would be nice also see this in documentation @RotBotSlicer as this is something I stumbled upon as well
