### ISSUE TITLE
Idea summary study link isnt working

### ISSUE THREAD

**Issue by DacianKing** [RotBotSlicer/Transform#5]
When you click on the researchgate link it says not found

**Comment by DacianKing** [comment]
Edit: There is also no saved version available

**Comment by RotBotSlicer** [comment]
The link seems to be correct, but clicking on it does not work (with any link). You will have to copy - paste it in browser. Then it should work. 
What do you mean by "there is also no saved version available"?

**Comment by DacianKing** [comment]
you are right. just have to make sure by removing the period after the link because it detects it as a part of the url and research gate says not found

**Comment by DacianKing** [comment]
This also maybe isnt the right place to ask, but for conic slicing are there are strength tests that have been done? To my understanding infill patterns matter in terms of tensile strength so I would like to see how it would perform vs for example triangular infill and support removal

**Comment by RotBotSlicer** [comment]
We have not made any strength tests yet. So I can not make a statement about strength...
